Lecture 08: Pandas

Numpy provides basic functionalities with multidimensional array structure built with homogeneous data. Pandas provides a lot of data manipulation functionalities on top of numpy using structures called DataFrames and Series. 

When would you use Pandas?
If you just need to read in a dataset before you use it, you can use numpy. If you need to do any amount of preprocessing with your data, pandas should be your go-to

Advantages of Pandas:
- Deals with missing values well (can still sort, fill in values, perform element-wise operations) without breaking. Missing values is a common issue when working with large datasets
- Very flexible: Easy to add columns/ rows, or combine dataframes together 
- Supports different types of data (doesn't need to be homogeneous)
- Good IO Capabilities
- Many high level data manipulation functionalities that don't exist or are much more inconvenient in numpy. 


Useful Cheatsheet:
https://s3.amazonaws.com/assets.datacamp.com/blog_assets/PandasPythonForDataScience.pdf

In [73]:
import numpy as np
import pandas as pd

First Data Structure: Series 
- 1-D labelled array holding any data type

In [75]:
s1 = pd.Series([2,5,1,4])
s2 = pd.Series([2,5,1,4], index = ['a','b','c','d'])

In [76]:
print(s1)
print("modified indexing")
print(s2)

0    2
1    5
2    1
3    4
dtype: int64
modified indexing
a    2
b    5
c    1
d    4
dtype: int64

Second Data Structure: DataFrames
- Think of it as a 2D analogue of series
- Similar to 2D numpy arrays with a number of functional advantages

Method 1: Creating data frame directly

In [79]:
# Data can be a numpy array or dictionary
# Can then create the dataframe using the data and with column order of your choosing
data = {'Code': ['Phys61',  'Phys63',  'Phys65'], 'Professor': ['Pat', 'Blas', 'Hari'], 'Course': ['Special Relativity',  'Electricity and Magnetism',  'Modern Physics']
}
df1 = pd.DataFrame(data, columns = ['Code', 'Course', 'Professor'])

     Code                     Course Professor
0  Phys61         Special Relativity       Pat
1  Phys63  Electricity and Magnetism      Blas
2  Phys65             Modern Physics      Hari

In [80]:
df1

     Code                     Course Professor
0  Phys61         Special Relativity       Pat
1  Phys63  Electricity and Magnetism      Blas
2  Phys65             Modern Physics      Hari

In [82]:
# Can check for types
df1.dtypes

Code         object
Course       object
Professor    object
dtype: object

METHOD 2: Reading a data file into a data frame
- Accomodates more than just csv files, can also read in multiple sheets from Excel 
- Very powerful I/O capabilities

In [83]:
sales_df = pd.read_csv('sample_data.csv', header=0)

In [84]:
sales_df

   OrderDate   Region       Rep     Item  Units  UnitCost     Total
0     1/6/16     East     Jones   Pencil     95      1.99    189.05
1    1/23/16  Central    Kivell   Binder     50     19.99     999.5
2     2/9/16  Central   Jardine   Pencil     36      4.99    179.64
3    2/26/16  Central      Gill      Pen     27     19.99    539.73
4    3/15/16     West   Sorvino   Pencil     56      2.99    167.44
5     4/1/16     East     Jones   Binder     60      4.99     299.4
6    4/18/16  Central   Andrews   Pencil     75      1.99    149.25
7     5/5/16  Central   Jardine   Pencil     90      4.99     449.1
8    5/22/16     West  Thompson   Pencil     32      1.99     63.68
9     6/8/16     East     Jones   Binder     60      8.99     539.4
10   6/25/16  Central    Morgan   Pencil     90      4.99     449.1
11   7/12/16     East    Howard   Binder     29      1.99     57.71
12   7/29/16     East    Parent   Binder     81     19.99  1,619.19
13   8/15/16     East     Jones   Pencil     35      4.99    174.65
14    9/1/16  Central     Smith     Desk      2    125.00       250
15   9/18/16     East     Jones  Pen Set     16     15.99    255.84
16   10/5/16  Central    Morgan   Binder     28      8.99    251.72
17  10/22/16     East     Jones      Pen     64      8.99    575.36
18   11/8/16     East    Parent      Pen     15     19.99    299.85
19  11/25/16  Central    Kivell  Pen Set     96      4.99    479.04
20  12/12/16  Central     Smith   Pencil     67      1.29     86.43
21  12/29/16     East    Parent  Pen Set     74     15.99  1,183.26
22   1/15/17  Central      Gill   Binder     46      8.99    413.54
23    2/1/17  Central     Smith   Binder     87     15.00  1,305.00
24   2/18/17     East     Jones   Binder      4      4.99     19.96
25    3/7/17     West   Sorvino   Binder      7     19.99    139.93
26   3/24/17  Central   Jardine  Pen Set     50      4.99     249.5
27   4/10/17  Central   Andrews   Pencil     66      1.99    131.34
28   4/27/17     East    Howard      Pen     96      4.99    479.04
29   5/14/17  Central      Gill   Pencil     53      1.29     68.37
30   5/31/17  Central      Gill   Binder     80      8.99     719.2
31   6/17/17  Central    Kivell     Desk      5    125.00       625
32    7/4/17     East     Jones  Pen Set     62      4.99    309.38
33   7/21/17  Central    Morgan  Pen Set     55     12.49    686.95
34    8/7/17  Central    Kivell  Pen Set     42     23.95  1,005.90
35   8/24/17     West   Sorvino     Desk      3    275.00       825
36   9/10/17  Central      Gill   Pencil      7      1.29      9.03
37   9/27/17     West   Sorvino      Pen     76      1.99    151.24
38  10/14/17     West  Thompson   Binder     57     19.99  1,139.43
39  10/31/17  Central   Andrews   Pencil     14      1.29     18.06
40  11/17/17  Central   Jardine   Binder     11      4.99     54.89
41   12/4/17  Central   Jardine   Binder     94     19.99  1,879.06
42  12/21/17  Central   Andrews   Binder     28      4.99    139.72

In [87]:
# Pick out a column
sales_df['Item']

0      Pencil
1      Binder
2      Pencil
3         Pen
4      Pencil
5      Binder
6      Pencil
7      Pencil
8      Pencil
9      Binder
10     Pencil
11     Binder
12     Binder
13     Pencil
14       Desk
15    Pen Set
16     Binder
17        Pen
18        Pen
19    Pen Set
20     Pencil
21    Pen Set
22     Binder
23     Binder
24     Binder
25     Binder
26    Pen Set
27     Pencil
28        Pen
29     Pencil
30     Binder
31       Desk
32    Pen Set
33    Pen Set
34    Pen Set
35       Desk
36     Pencil
37        Pen
38     Binder
39     Pencil
40     Binder
41     Binder
42     Binder
Name: Item, dtype: object

In [88]:
# Can pick out multiple columns with a list
sales_df[["Region", "Rep"]]

     Region       Rep
0      East     Jones
1   Central    Kivell
2   Central   Jardine
3   Central      Gill
4      West   Sorvino
5      East     Jones
6   Central   Andrews
7   Central   Jardine
8      West  Thompson
9      East     Jones
10  Central    Morgan
11     East    Howard
12     East    Parent
13     East     Jones
14  Central     Smith
15     East     Jones
16  Central    Morgan
17     East     Jones
18     East    Parent
19  Central    Kivell
20  Central     Smith
21     East    Parent
22  Central      Gill
23  Central     Smith
24     East     Jones
25     West   Sorvino
26  Central   Jardine
27  Central   Andrews
28     East    Howard
29  Central      Gill
30  Central      Gill
31  Central    Kivell
32     East     Jones
33  Central    Morgan
34  Central    Kivell
35     West   Sorvino
36  Central      Gill
37     West   Sorvino
38     West  Thompson
39  Central   Andrews
40  Central   Jardine
41  Central   Jardine
42  Central   Andrews

In [90]:
# Supports index slicing as well 
sales_df[1:5]

  OrderDate   Region      Rep    Item  Units  UnitCost   Total
1   1/23/16  Central   Kivell  Binder     50     19.99   999.5
2    2/9/16  Central  Jardine  Pencil     36      4.99  179.64
3   2/26/16  Central     Gill     Pen     27     19.99  539.73
4   3/15/16     West  Sorvino  Pencil     56      2.99  167.44

DATA SELECTION METHODS
1. iloc is location/index based
2. loc is label based
3. ix is like loc but default to iloc when no label is specified. Kind of like combination of both

In [92]:
# Parameters can be list, value, or slice of columns / rows. 

print("Example 1: By Index")
print(sales_df.iloc[0:5,[1,3,5]])
print("Example 2: By Label")
print(sales_df.loc[sales_df['Region'] == "West", "Rep"])
print("Example 3: By Label")
print(sales_df.loc[(sales_df["UnitCost"] < 2.0) | (sales_df["UnitCost"] > 10.0), sales_df.columns])

Example 1: By Index
    Region    Item  UnitCost
0     East  Pencil      1.99
1  Central  Binder     19.99
2  Central  Pencil      4.99
3  Central     Pen     19.99
4     West  Pencil      2.99
Example 2: By Label
4      Sorvino
8     Thompson
25     Sorvino
35     Sorvino
37     Sorvino
38    Thompson
Name: Rep, dtype: object
Example 3: By Label
   OrderDate   Region       Rep     Item  Units  UnitCost     Total
0     1/6/16     East     Jones   Pencil     95      1.99    189.05
1    1/23/16  Central    Kivell   Binder     50     19.99     999.5
3    2/26/16  Central      Gill      Pen     27     19.99    539.73
6    4/18/16  Central   Andrews   Pencil     75      1.99    149.25
8    5/22/16     West  Thompson   Pencil     32      1.99     63.68
11   7/12/16     East    Howard   Binder     29      1.99     57.71
12   7/29/16     East    Parent   Binder     81     19.99  1,619.19
14    9/1/16  Central     Smith     Desk      2    125.00       250
15   9/18/16     East     Jones  Pen Set     16     15.99    255.84
18   11/8/16     East    Parent      Pen     15     19.99    299.85
20  12/12/16  Central     Smith   Pencil     67      1.29     86.43
21  12/29/16     East    Parent  Pen Set     74     15.99  1,183.26
23    2/1/17  Central     Smith   Binder     87     15.00  1,305.00
25    3/7/17     West   Sorvino   Binder      7     19.99    139.93
27   4/10/17  Central   Andrews   Pencil     66      1.99    131.34
29   5/14/17  Central      Gill   Pencil     53      1.29     68.37
31   6/17/17  Central    Kivell     Desk      5    125.00       625
33   7/21/17  Central    Morgan  Pen Set     55     12.49    686.95
34    8/7/17  Central    Kivell  Pen Set     42     23.95  1,005.90
35   8/24/17     West   Sorvino     Desk      3    275.00       825
36   9/10/17  Central      Gill   Pencil      7      1.29      9.03
37   9/27/17     West   Sorvino      Pen     76      1.99    151.24
38  10/14/17     West  Thompson   Binder     57     19.99  1,139.43
39  10/31/17  Central   Andrews   Pencil     14      1.29     18.06
41   12/4/17  Central   Jardine   Binder     94     19.99  1,879.06

SORTING METHODS: sort_index, sort_values

In [94]:
# Sorts by column names (alphabetically)
sales_df.sort_index(1)

       Item OrderDate   Region       Rep     Total  UnitCost  Units
0    Pencil    1/6/16     East     Jones    189.05      1.99     95
1    Binder   1/23/16  Central    Kivell     999.5     19.99     50
2    Pencil    2/9/16  Central   Jardine    179.64      4.99     36
3       Pen   2/26/16  Central      Gill    539.73     19.99     27
4    Pencil   3/15/16     West   Sorvino    167.44      2.99     56
5    Binder    4/1/16     East     Jones     299.4      4.99     60
6    Pencil   4/18/16  Central   Andrews    149.25      1.99     75
7    Pencil    5/5/16  Central   Jardine     449.1      4.99     90
8    Pencil   5/22/16     West  Thompson     63.68      1.99     32
9    Binder    6/8/16     East     Jones     539.4      8.99     60
10   Pencil   6/25/16  Central    Morgan     449.1      4.99     90
11   Binder   7/12/16     East    Howard     57.71      1.99     29
12   Binder   7/29/16     East    Parent  1,619.19     19.99     81
13   Pencil   8/15/16     East     Jones    174.65      4.99     35
14     Desk    9/1/16  Central     Smith       250    125.00      2
15  Pen Set   9/18/16     East     Jones    255.84     15.99     16
16   Binder   10/5/16  Central    Morgan    251.72      8.99     28
17      Pen  10/22/16     East     Jones    575.36      8.99     64
18      Pen   11/8/16     East    Parent    299.85     19.99     15
19  Pen Set  11/25/16  Central    Kivell    479.04      4.99     96
20   Pencil  12/12/16  Central     Smith     86.43      1.29     67
21  Pen Set  12/29/16     East    Parent  1,183.26     15.99     74
22   Binder   1/15/17  Central      Gill    413.54      8.99     46
23   Binder    2/1/17  Central     Smith  1,305.00     15.00     87
24   Binder   2/18/17     East     Jones     19.96      4.99      4
25   Binder    3/7/17     West   Sorvino    139.93     19.99      7
26  Pen Set   3/24/17  Central   Jardine     249.5      4.99     50
27   Pencil   4/10/17  Central   Andrews    131.34      1.99     66
28      Pen   4/27/17     East    Howard    479.04      4.99     96
29   Pencil   5/14/17  Central      Gill     68.37      1.29     53
30   Binder   5/31/17  Central      Gill     719.2      8.99     80
31     Desk   6/17/17  Central    Kivell       625    125.00      5
32  Pen Set    7/4/17     East     Jones    309.38      4.99     62
33  Pen Set   7/21/17  Central    Morgan    686.95     12.49     55
34  Pen Set    8/7/17  Central    Kivell  1,005.90     23.95     42
35     Desk   8/24/17     West   Sorvino       825    275.00      3
36   Pencil   9/10/17  Central      Gill      9.03      1.29      7
37      Pen   9/27/17     West   Sorvino    151.24      1.99     76
38   Binder  10/14/17     West  Thompson  1,139.43     19.99     57
39   Pencil  10/31/17  Central   Andrews     18.06      1.29     14
40   Binder  11/17/17  Central   Jardine     54.89      4.99     11
41   Binder   12/4/17  Central   Jardine  1,879.06     19.99     94
42   Binder  12/21/17  Central   Andrews    139.72      4.99     28

In [96]:
# Sort by unitcost
sales_df.sort_values("UnitCost")

   OrderDate   Region       Rep     Item  Units  UnitCost     Total
39  10/31/17  Central   Andrews   Pencil     14      1.29     18.06
29   5/14/17  Central      Gill   Pencil     53      1.29     68.37
36   9/10/17  Central      Gill   Pencil      7      1.29      9.03
20  12/12/16  Central     Smith   Pencil     67      1.29     86.43
0     1/6/16     East     Jones   Pencil     95      1.99    189.05
27   4/10/17  Central   Andrews   Pencil     66      1.99    131.34
11   7/12/16     East    Howard   Binder     29      1.99     57.71
8    5/22/16     West  Thompson   Pencil     32      1.99     63.68
6    4/18/16  Central   Andrews   Pencil     75      1.99    149.25
37   9/27/17     West   Sorvino      Pen     76      1.99    151.24
4    3/15/16     West   Sorvino   Pencil     56      2.99    167.44
28   4/27/17     East    Howard      Pen     96      4.99    479.04
40  11/17/17  Central   Jardine   Binder     11      4.99     54.89
26   3/24/17  Central   Jardine  Pen Set     50      4.99     249.5
24   2/18/17     East     Jones   Binder      4      4.99     19.96
32    7/4/17     East     Jones  Pen Set     62      4.99    309.38
19  11/25/16  Central    Kivell  Pen Set     96      4.99    479.04
42  12/21/17  Central   Andrews   Binder     28      4.99    139.72
2     2/9/16  Central   Jardine   Pencil     36      4.99    179.64
5     4/1/16     East     Jones   Binder     60      4.99     299.4
7     5/5/16  Central   Jardine   Pencil     90      4.99     449.1
13   8/15/16     East     Jones   Pencil     35      4.99    174.65
10   6/25/16  Central    Morgan   Pencil     90      4.99     449.1
30   5/31/17  Central      Gill   Binder     80      8.99     719.2
16   10/5/16  Central    Morgan   Binder     28      8.99    251.72
22   1/15/17  Central      Gill   Binder     46      8.99    413.54
17  10/22/16     East     Jones      Pen     64      8.99    575.36
9     6/8/16     East     Jones   Binder     60      8.99     539.4
33   7/21/17  Central    Morgan  Pen Set     55     12.49    686.95
23    2/1/17  Central     Smith   Binder     87     15.00  1,305.00
21  12/29/16     East    Parent  Pen Set     74     15.99  1,183.26
15   9/18/16     East     Jones  Pen Set     16     15.99    255.84
25    3/7/17     West   Sorvino   Binder      7     19.99    139.93
41   12/4/17  Central   Jardine   Binder     94     19.99  1,879.06
3    2/26/16  Central      Gill      Pen     27     19.99    539.73
38  10/14/17     West  Thompson   Binder     57     19.99  1,139.43
1    1/23/16  Central    Kivell   Binder     50     19.99     999.5
12   7/29/16     East    Parent   Binder     81     19.99  1,619.19
18   11/8/16     East    Parent      Pen     15     19.99    299.85
34    8/7/17  Central    Kivell  Pen Set     42     23.95  1,005.90
31   6/17/17  Central    Kivell     Desk      5    125.00       625
14    9/1/16  Central     Smith     Desk      2    125.00       250
35   8/24/17     West   Sorvino     Desk      3    275.00       825

This tutorial only scratches the surface of what Pandas can do! There's so much more to take advantage of when the need arises. 

Some other potentially useful functions include:
1. Functions like median, mean, min, max, sum also exist in pandas. Does a good job of supporting missing values.
2. map/ apply/ applymap 
3. Whole lot more!